### ISSUE TITLE
Accessing and setting document metadata directly vs through `_meta`

### ISSUE THREAD

**Issue by dcwatson** [elasticsearch/elasticsearch-dsl-py#58]
If you define a "score" field on a DocType, the ``_meta.score`` attribute is set to the document value rather than the ``_score`` attribute of the ES hit. I think this is due to ``ObjectBase.__init__`` calling setattr, and the ``__setattr__`` of DocType making a special case for META_FIELDS (which include "score") to set attributes on ``_meta``. I'd imagine this is the case for any document field with the same name as a meta field.

It seems like DocType shouldn't try to expose/set ``_meta`` attributes directly. Or at least document which field names are not allowed on a DocType and raise an error if you try to define one that conflicts with ``_meta``.

**Comment by HonzaKral** [comment]
Thanks for the report, I agree that this behavior is not desirable in most cases. For the time being I changed it that only metadata relevant to the document `('id', 'parent', 'routing', 'timestamp', 'ttl', 'version', 'version_type')` can be set that way. It still limits the namespace but I feel like this is a good compromise since people might want to set these directly.

What do you think?

**Comment by dcwatson** [comment]
It still seems like unexpected behavior to have document fields overwrite ``_meta`` fields. If these names are going to be used get/set ``_meta`` fields, I still think it's a good idea to disallow defining them on a ``DocType``.

**Comment by HonzaKral** [comment]
I see your point, I am just not sure for the document metadata - like `parent`, `id` etc. To me they seem like they should be accessible (and settable) on the document itself. I will think about it more.

Of course if anybody has an opinion I welcome the feedback, feel free to comment here.

**Comment by dcwatson** [comment]
Right now, this will throw a NumberFormatException exception, since ES ``version`` is expected to be an integer:

```python
class Release (DocType):
    package = String(analyzer='snowball', fields={'raw': String(index='not_analyzed')})
    version = String(index='not_analyzed')

    class Meta:
        index = 'software'

r = Release(package='elasticsearch', version='1.4.3')
```

I think there are probably other errors that may arise from conflating document fields with ES metadata.

**Comment by HonzaKral** [comment]
Very good point. If we flip it and check for defined fields would it make more sense?

I am starting to lean towards your solution, just want to think it over. Thanks for the feedback and the patience!

**Comment by dcwatson** [comment]
I'm not sure I understand what you mean. Do you mean if you define a ``version`` field, ``doc.version`` will use that, otherwise it gets/sets ``_meta.version``? That would work, but feels a bit magical to me.

Thanks for considering, and for your work on this library.

**Comment by HonzaKral** [comment]
Thanks for you patience again, it was very helpful. I removed the access to all the metadata fields except `id` which I feel is needed.

**Comment by robhudson** [comment]
I'm not getting an error `TypeError: DocTypeMeta object got multiple values for keyword argument 'id'` because our `DocType` subclass contains an `id` field.

IMHO, I think the document fields and ES meta information should remain separate.

**Comment by HonzaKral** [comment]
So I only left the `id` accessible as a property. I can definitely fix the code so that your error doesn't appear, but the question is what is the expected/wanted behavior.

I can see arguments both ways. Why I want `id` to be accessible without `_meta` namespace:

 * accessing `_meta` shouldn't be needed to just save a document
 * some systems (django templates) doesn't allow access to protected attributes
 * `id` is, to me, a natural part of the document

Why it should be just inside:

 * feels magical (arbitrary, not straightforward)
 * easier implementation (and reasoning about what goes where)
 * can conflict with field `id` people might have on their `DocType`

**Comment by robhudson** [comment]
If I understand the code correctly, this will pull the `_id` field from the result and set it as an attribute on the DocType class with the name `id` as part of the results list. My feeling would that es-dsl should only set attributes based on the defined fields. I might be surprised to see the `id` there if I didn't define it.

> accessing _meta shouldn't be needed to just save a document

I'm not sure exactly what this means? In code I've written I set `_id` explicitly when indexing?

> some systems (django templates) doesn't allow access to protected attributes

I'm less concerned about this. I agree, it is an annoyance, but there are ways to work around it, like template tags or putting the data into the template context in a view, if needed.

IIRC, elasticutils worked around this by calling it `es_meta`. It would make sense to me that `_id` was set on `_meta` (or `es_meta`) as `_meta.id`.

> id is, to me, a natural part of the document

My feeling is that es-dsl shouldn't make any assumptions or enforce restrictions on my data.

I'm curious what others opinions are.

**Comment by HonzaKral** [comment]
I like the idea of renaming it to `es_meta`. There is a name conflict chance of course, but should be minimal (especially when compared to `id` :) ).

Then there are two other questions:

Currently you can say: `Comment(title='hello', _parent='blog-post-1').save()` and we will extract `_parent` and use it as a parent value, same would go for version etc. Do we want to keep that? (imho yes since otherwise creating a child document in the dsl would be at least a two step process: `c = Comment(title='hello'); c.es_meta.parent = 'blog-post-1'; c.save()`.

Or would something like `Comment(title='hello', es_meta={'parent': 'blog-post-1'})` be ok? (that one we would definitely have to be used in `from_es`)

@robhudson what I meant by "you shouldn't need to access `_meta` was that without it it would be impossible to create a document by hand and save it into elasticsearch with a manually assigned ID, imo not acceptable (and still a hassle if we rename it to `es_meta`)

Thanks for the discussion guys, I really appreciate the feedback and help in designing this.

**Comment by jezdez** [comment]
FWIW I don't think we can easily compare Django's model classes with this one, which I think we all have in mind when we talk about `id` fields. But to me the native behavior of ES is to set an id field and there is a option to override it with custom content. The DSL should reflect that, just like other "special" fields such as `_parent` or `_version`.

I think the conceptual disconnect happens when trying to overcome the differences between the list of fields as class attributes and the initialization parameters when creating result objects: The class attributes don't distinguish between native fields and custom fields while the initialization parameter do. So I would guess a solution would be to decide for one level of abstraction:

```python
from esdsl import document, field


class MyDocumentType(document.DocType):
    id = field.Long()
    content = field.String()


result = MyDocumentType(id='123', content'acme')

print(result.id)
```

or:

```python
from esdsl import document, field


class MyDocumentType(document.DocType):
    content = field.String()

    class Meta:
        id = field.Long()


result = MyDocumentType(content'acme', meta={'id': _id})

print(result.meta.id)
print(result._id) # works also for _version etc
```

**Comment by HonzaKral** [comment]
So another iteration is available for review in `es-meta` branch. Short summary:

 * all meta fields (on both `Result` and `DocType`) are accessible on `.meta` property (`hit.meta.score`, `Post(meta={'id': 42})`,  `doc.meta.id = 42`, `doc.meta.parent`, ...)
 * you can also access (read and write) them on `DocType` using their underscored form (`Post(_id=42)`, `doc._id = 42`, ...)

**Comment by robhudson** [comment]
I like the solution you came up with. It does mean that you cannot have a field on your documents named `meta`, but that seems like a lesser limitation than not being able to have `id`. Perhaps that should be mentioned in the documentation somewhere?

**Comment by HonzaKral** [comment]
Yes, we need to document it. Though you can still have a field called `meta` and access it via `doc['meta']`

Thanks all for the discussion and design opinions, it made a lot of difference.

**Comment by goodrichj** [comment]
Does any of this impact _meta usage? https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-meta-field.html

**Comment by HonzaKral** [comment]
No, that works fine, though it is very `meta` you can still define it:

    from elasticsearch_dsl import DocType, MetaField
    class MyDoc(DocType):
        class Meta:
            meta = MetaField(cls='some class')
