### ISSUE TITLE
When creating a DocType instance from results, save highlights somewhere

### ISSUE THREAD

**Issue by HonzaKral** [elasticsearch/elasticsearch-dsl-py#62]
I don't think `_meta` is a good option since it won't be accessible in django templates for example.

**Comment by dcwatson** [comment]
Since `_meta` was renamed `meta`, the original point about Django templates may be moot. Maybe a `result.meta.highlight` dictionary? It would be slightly different than the rest, in that `highlight` is not underscored in the ES response, but I think putting it in `meta` is still better than a `highlight` attribute directly on documents.

I can take a pass with a PR if you want?

**Comment by HonzaKral** [comment]
a PR would be most welcome of course!
